language: python
python:
    - "3.6"
# install dependancies
install:
    - cd API

    # set environment variables
    - export FLASK_APP="app.py"
    - export APP_MODE='dev'
    - pip install -r requirements.txt
# run tests
script:
    - python app.py
    - python test_app.py
    - python test_endpoints.py
# run coverage tests
after_success: 
    - coverage run --source='.' --omit='run.py','settings.py','openapi.py' test_endpoints.py
    - coveralls