language: python
python:
    - "2.7"
    - "3.6"
# install dependancies
install:
    - cd API

    # set environment variables
    - export FLASK_APP="app.py"

    - pip install -r requirements.txt
# run tests
script:
    - python test_app.py
    - python test_endpoints.py
