language: python
python:
    - "2.7"
    - "3.6"
# install dependancies
install:
    - cd api

    # set environment variables
    - export FLASK_APP="run.py"
    - export APP_MODE='dev'
    - export SECRET='1aodfadfjo23erofoasdfuoaisdufadadfuo32'
    - export DEFAULT_ADMIN_USERNAME='admin'
    - export DEFAULT_ADMIN_PASSWORD='super-secret'
    - export DEFAULT_ADMIN_EMAIL='bam@admin.com'
    - export JWT_SECRET_KEY='aoaudfouaeoru23432oiuriuiaudsfiadf'

    - pip install -r requirements.txt
# run tests
script:
    - nosetests test_endpoints.py
# run coverage tests
after_success: 
    - coverage run --source='.' --omit='run.py','settings.py','openapi.py' test_endpoints.py
    - coveralls