language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - source ./.travis.sh
  - psql -c 'create database testchal_Booka_meal;' -U postgres

script: 

- cd api
- ls la

- nosetests --with-coverage --cover-package app

after_success:

  - coveralls