language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - cd API
  - ls -la 
  
script: 
  
  - nose2 test_app.py
  - nose2 test_endpoints.py

after_success:

  - coverage run --source='.' --omit='app.py','config.py','Test.py' test_app.py test_endpoints.py
  - coveralls