language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - cd API
  - ls -la 
  
script: 
  
  - python test_app.py
  - python test_endpoints.py


after_success:

  - coverage run --source='.' --omit='app.py','config.py','caterer.py','user.py'  test_app.py
  - coveralls